<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/14.0.1">
    <PropertyGroup>
        <Authors></Authors>
        <Company></Company>
        <Version>1.6.5.0</Version>
        <Description>A plugin that keeps track of HP/MP/GP ticks.</Description>
        <Copyright></Copyright>
        <PackageProjectUrl>https://github.com/Kurochi51/TickTracker</PackageProjectUrl>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Platforms>x64</Platforms>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <ContentWithTargetPath Include="..\Images\icon.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>Images\icon.png</TargetPath>
        </ContentWithTargetPath>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Meziantou.Analyzer" Version="2.0.212">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Penumbra.Api" Version="5.10.0" />
    </ItemGroup>

    <!--
    <ItemGroup>
        <Reference Include="Dalamud">
            <HintPath>D:\yes\Dalamud\bin\Release\Dalamud.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="FFXIVClientStructs">
            <HintPath>>D:\yes\Dalamud\bin\Release\FFXIVClientStructs.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="InteropGenerator.Runtime">
            <HintPath>>D:\yes\Dalamud\bin\Release\InteropGenerator.Runtime.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Newtonsoft.Json">
            <HintPath>>D:\yes\Dalamud\bin\Release\Newtonsoft.Json.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Dalamud.Bindings.ImGui">
            <HintPath>>D:\yes\Dalamud\bin\Release\Dalamud.Bindings.ImGui.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Dalamud.Bindings.ImPlot">
            <HintPath>>D:\yes\Dalamud\bin\Release\Dalamud.Bindings.ImPlot.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Dalamud.Bindings.ImGuizmo">
            <HintPath>>D:\yes\Dalamud\bin\Release\Dalamud.Bindings.ImGuizmo.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Lumina">
            <HintPath>>D:\yes\Dalamud\bin\Release\Lumina.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Lumina.Excel">
            <HintPath>>D:\yes\Dalamud\bin\Release\Lumina.Excel.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>
    -->

</Project>
